



"""
app/recommender/features.py

Feature extraction module for the
Movie Recommendation System.

Responsibilities:
1. Load the cleaned movie dataset.
2. Validate the required columns.
3. Prepare movie descriptions and genres.
4. Convert text into TF-IDF vectors.
5. Return the fitted vectorizer and feature matrix.

The training module will save the generated
features to the artifacts directory.
"""

import logging

import pandas as pd

from sklearn.feature_extraction.text import (
    TfidfVectorizer,
)

from app.config import CLEANED_MOVIES_PATH


# --------------------------------------------------
# 1. LOGGING
# --------------------------------------------------

logger = logging.getLogger(__name__)


# --------------------------------------------------
# 2. LOAD CLEANED DATASET
# --------------------------------------------------

def load_cleaned_dataset():
    """
    Load the dataset generated by preprocess.py.

    Returns:
        pandas.DataFrame
    """

    if not CLEANED_MOVIES_PATH.exists():
        raise FileNotFoundError(
            "Cleaned dataset not found. "
            "Run preprocess.py first: "
            f"{CLEANED_MOVIES_PATH}"
        )

    df = pd.read_csv(
        CLEANED_MOVIES_PATH,
        keep_default_na=False,
    )

    logger.info(
        "Loaded %s cleaned movie records",
        len(df),
    )

    return df


# --------------------------------------------------
# 3. VALIDATE FEATURE DATA
# --------------------------------------------------

def validate_feature_data(df):
    """
    Check that the dataset contains the columns
    required for feature extraction.
    """

    required_columns = {
        "id",
        "title",
        "combined_features",
    }

    missing = required_columns - set(df.columns)

    if missing:
        raise ValueError(
            "Missing required columns: "
            f"{sorted(missing)}"
        )

    if df.empty:
        raise ValueError(
            "The cleaned dataset is empty."
        )

    if df["id"].isna().any():
        raise ValueError(
            "Movie IDs cannot be missing."
        )

    if df["id"].duplicated().any():
        raise ValueError(
            "Duplicate movie IDs detected."
        )

    return df


# --------------------------------------------------
# 4. PREPARE TEXT FEATURES
# --------------------------------------------------

def prepare_text_features(df):
    """
    Prepare combined_features for TF-IDF.

    Returns:
        pandas.Series
    """

    df = validate_feature_data(df)

    text_data = (
        df["combined_features"]
        .fillna("")
        .astype(str)
        .str.strip()
    )

    if text_data.eq("").all():
        raise ValueError(
            "All movie descriptions are empty."
        )

    return text_data


# --------------------------------------------------
# 5. CREATE TF-IDF VECTORIZER
# --------------------------------------------------

def create_vectorizer():
    """
    Configure the TF-IDF vectorizer.

    Returns:
        TfidfVectorizer
    """

    vectorizer = TfidfVectorizer(
        stop_words="english",
        lowercase=True,
        strip_accents="unicode",
        ngram_range=(1, 2),
        min_df=1,
        max_df=1.0,
        sublinear_tf=True,
        norm="l2",
    )

    return vectorizer


# --------------------------------------------------
# 6. EXTRACT TF-IDF FEATURES
# --------------------------------------------------

def extract_features(df):
    """
    Fit TF-IDF on the movie text and transform
    it into a numerical feature matrix.

    Args:
        df: Cleaned movie DataFrame.

    Returns:
        tuple:
            vectorizer
            feature_matrix
    """

    text_data = prepare_text_features(df)

    logger.info(
        "Extracting TF-IDF features..."
    )

    vectorizer = create_vectorizer()

    feature_matrix = vectorizer.fit_transform(
        text_data
    )

    logger.info(
        "TF-IDF feature matrix shape: %s",
        feature_matrix.shape,
    )

    return vectorizer, feature_matrix


# --------------------------------------------------
# 7. TRANSFORM NEW TEXT
# --------------------------------------------------

def transform_text(vectorizer, text):
    """
    Transform new movie text using an already
    fitted TF-IDF vectorizer.

    Do not refit the vectorizer here.

    Args:
        vectorizer: Fitted TfidfVectorizer.
        text: Movie description or combined text.

    Returns:
        Sparse feature matrix.
    """

    if not isinstance(text, str):
        raise TypeError(
            "Movie text must be a string."
        )

    if not text.strip():
        raise ValueError(
            "Movie text cannot be empty."
        )

    return vectorizer.transform([text])


# --------------------------------------------------
# 8. MAIN FUNCTION FOR TESTING
# --------------------------------------------------

def main():
    """
    Test feature extraction independently.
    """

    logging.basicConfig(
        level=logging.INFO,
        format="%(levelname)s: %(message)s",
    )

    df = load_cleaned_dataset()

    vectorizer, feature_matrix = (
        extract_features(df)
    )

    print(
        "Number of movies:",
        feature_matrix.shape[0],
    )

    print(
        "Number of TF-IDF features:",
        feature_matrix.shape[1],
    )

    print(
        "First 20 vocabulary terms:",
        vectorizer.get_feature_names_out()[:20],
    )


if __name__ == "__main__":
    main()