



"""
app/recommender/predict.py

Prediction module for the Movie Recommendation System.

Responsibilities:
1. Load trained model artifacts.
2. Map movie IDs to feature-matrix rows.
3. Calculate cosine similarity.
4. Exclude the selected movie.
5. Rank movies by similarity.
6. Return the top N recommendations.

This module does not retrain the model
or directly access the database.
"""

import logging
from pathlib import Path

import joblib
import numpy as np

from sklearn.metrics.pairwise import (
    cosine_similarity,
)

from app.config import (
    VECTORIZER_PATH,
    FEATURE_MATRIX_PATH,
    MOVIE_IDS_PATH,
    TOP_N_RECOMMENDATIONS,
    MAX_RECOMMENDATIONS,
)


logger = logging.getLogger(__name__)


# --------------------------------------------------
# 1. RECOMMENDATION ENGINE
# --------------------------------------------------

class MovieRecommender:
    """
    Content-based movie recommendation engine.

    Loads previously trained TF-IDF artifacts
    and generates recommendations using
    cosine similarity.
    """

    def __init__(self):
        self.vectorizer = None
        self.feature_matrix = None
        self.movie_ids = None
        self.movie_id_to_index = {}

        self.is_loaded = False

    # --------------------------------------------------
    # 2. LOAD MODEL ARTIFACTS
    # --------------------------------------------------

    def load_model(self):
        """
        Load the trained vectorizer,
        feature matrix and movie IDs.
        """

        artifact_paths = [
            VECTORIZER_PATH,
            FEATURE_MATRIX_PATH,
            MOVIE_IDS_PATH,
        ]

        for path in artifact_paths:
            if not Path(path).exists():
                raise FileNotFoundError(
                    f"Missing artifact: {path}. "
                    "Run train.py first."
                )

        logger.info(
            "Loading recommendation model..."
        )

        # Load artifacts generated by train.py.
        # Only load trusted joblib files.
        vectorizer = joblib.load(
            VECTORIZER_PATH
        )

        feature_matrix = joblib.load(
            FEATURE_MATRIX_PATH
        )

        movie_ids = joblib.load(
            MOVIE_IDS_PATH
        )

        # Validate artifact consistency.
        if feature_matrix.shape[0] != len(movie_ids):
            raise ValueError(
                "Feature matrix and movie IDs "
                "have different lengths."
            )

        if len(set(movie_ids)) != len(movie_ids):
            raise ValueError(
                "Duplicate movie IDs found "
                "in saved artifacts."
            )

        if not hasattr(vectorizer, "vocabulary_"):
            raise ValueError(
                "Saved TF-IDF vectorizer "
                "is not fitted."
            )

        if (
            feature_matrix.shape[1]
            != len(vectorizer.vocabulary_)
        ):
            raise ValueError(
                "Vectorizer vocabulary and "
                "feature matrix do not match."
            )

        # Assign only after validation succeeds.
        self.vectorizer = vectorizer
        self.feature_matrix = feature_matrix
        self.movie_ids = [
            int(movie_id)
            for movie_id in movie_ids
        ]

        # Map movie IDs to matrix row indexes.
        self.movie_id_to_index = {
            movie_id: index
            for index, movie_id
            in enumerate(self.movie_ids)
        }

        self.is_loaded = True

        logger.info(
            "Loaded model with %s movies.",
            len(self.movie_ids),
        )

    # --------------------------------------------------
    # 3. GET MOVIE INDEX
    # --------------------------------------------------

    def get_movie_index(self, movie_id: int):
        """
        Find the feature-matrix row
        corresponding to a movie ID.
        """

        if not self.is_loaded:
            self.load_model()

        index = self.movie_id_to_index.get(
            movie_id
        )

        if index is None:
            raise ValueError(
                f"Movie ID {movie_id} "
                "was not found in the model."
            )

        return index

    # --------------------------------------------------
    # 4. CALCULATE SIMILARITY
    # --------------------------------------------------

    def calculate_similarity(
        self,
        movie_id: int,
    ):
        """
        Calculate cosine similarity between
        one movie and all movies.

        Returns:
            NumPy array of similarity scores.
        """

        movie_index = self.get_movie_index(
            movie_id
        )

        # Extract the selected movie's vector.
        movie_vector = self.feature_matrix[
            movie_index
        ]

        # Compare it with all movie vectors.
        similarity_scores = cosine_similarity(
            movie_vector,
            self.feature_matrix,
        ).flatten()

        return similarity_scores

    # --------------------------------------------------
    # 5. GENERATE RECOMMENDATIONS
    # --------------------------------------------------

    def recommend(
        self,
        movie_id: int,
        top_n: int = TOP_N_RECOMMENDATIONS,
    ):
        """
        Return the most similar movies.

        Args:
            movie_id: Selected movie ID.
            top_n: Number of recommendations.

        Returns:
            List of dictionaries containing
            movie_id and similarity_score.
        """

        if not 1 <= top_n <= MAX_RECOMMENDATIONS:
            raise ValueError(
                "top_n must be between 1 and "
                f"{MAX_RECOMMENDATIONS}."
            )

        # Find the selected movie's row.
        movie_index = self.get_movie_index(
            movie_id
        )

        # Calculate similarity.
        similarity_scores = (
            self.calculate_similarity(movie_id)
        )

        # Exclude the selected movie.
        similarity_scores[movie_index] = -1.0

        # Sort by similarity (highest first).
        # mergesort preserves original row order
        # for equal similarity scores.
        ranked_indices = np.argsort(
            -similarity_scores,
            kind="mergesort",
        )

        # Select the top N other movies.
        top_indices = ranked_indices[
            :min(top_n, len(self.movie_ids) - 1)
        ]

        recommendations = []

        for index in top_indices:
            recommendations.append({
                "movie_id": self.movie_ids[index],
                "similarity_score": round(
                    float(similarity_scores[index]),
                    4,
                ),
            })

        return recommendations


# --------------------------------------------------
# 6. MAIN FUNCTION FOR TESTING
# --------------------------------------------------

def main():
    """
    Test the recommendation engine
    independently.
    """

    logging.basicConfig(
        level=logging.INFO,
        format="%(levelname)s: %(message)s",
    )

    recommender = MovieRecommender()

    recommender.load_model()

    # Movie ID 19995 exists in the current TMDB dataset.
    selected_movie_id = 19995

    results = recommender.recommend(
        movie_id=selected_movie_id,
        top_n=5,
    )

    print("\nRecommended Movies")
    print("-" * 45)

    for rank, movie in enumerate(
        results,
        start=1,
    ):
        print(
            f"{rank}. Movie ID: "
            f"{movie['movie_id']} | "
            f"Similarity: "
            f"{movie['similarity_score']:.4f}"
        )


if __name__ == "__main__":
    main()